# Generated by Django 4.0.6 on 2024-02-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='place',
            field=models.CharField(max_length=100),
        ),
    ]
