# Generated by Django 4.0.6 on 2024-02-15 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_places_place'),
        ('hotel', '0002_alter_hotel_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.place'),
        ),
    ]
