# Generated by Django 5.0 on 2024-02-18 14:21

import django.db.models.deletion
import hotel.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotel", "0004_hotel_overview_hotel_review"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotel",
            name="overview",
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name="hotel_review",
            name="rate",
            field=models.IntegerField(
                validators=[hotel.models.Hotel_Review.validate_max_value]
            ),
        ),
        migrations.CreateModel(
            name="Hotel_Booking",
            fields=[
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("valid_date_from", models.DateField(default=None)),
                ("valid_date_till", models.DateField(default=None)),
                ("no_room_booking", models.IntegerField()),
                ("total_price", models.IntegerField()),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hotel.hotel"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
            },
        ),
    ]
