# Generated by Django 4.0.6 on 2024-02-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_alter_hotel_overview_alter_hotel_review_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='map_link',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='overview',
            field=models.TextField(max_length=1000),
        ),
    ]
