# Generated by Django 5.0.2 on 2024-03-17 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_rename_hotel_booking_hotelbooking_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelfacilitys',
            name='hotel',
        ),
    ]
