# Generated by Django 4.1.3 on 2024-04-11 10:59

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_remove_hotelfacilitys_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotel_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='hotelname', unique=True),
        ),
    ]
