# Generated by Django 5.0 on 2024-02-19 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bus", "0001_initial"),
        ("core", "0004_rename_places_place"),
        ("hotel", "0005_alter_hotel_overview_alter_hotel_review_rate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tour_Type",
            fields=[
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Tour",
            fields=[
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("map_link", models.URLField()),
                ("rating", models.FloatField(default=0, null=True)),
                ("overview", models.TextField(max_length=500)),
                ("no_of_day", models.IntegerField()),
                ("Itinerary", models.TextField(max_length=500)),
                ("start_date", models.DateField(default=None)),
                ("end_date", models.DateField(default=None)),
                ("tour_image", models.ImageField(upload_to="image/tour/")),
                ("image_2", models.ImageField(upload_to="image/tour/")),
                ("image_3", models.ImageField(upload_to="image/tour/")),
                ("buses", models.ManyToManyField(related_name="tours", to="bus.bus")),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.city"
                    ),
                ),
                (
                    "hotels",
                    models.ManyToManyField(related_name="tours", to="hotel.hotel"),
                ),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.place"
                    ),
                ),
                (
                    "tour_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="type",
                        to="tour.tour_type",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
