# Generated by Django 4.0.6 on 2024-02-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_bus_seat_alter_bus_bus_company_image_and_more'),
        ('tour', '0002_tour_group_size_tour_total_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterModelOptions(
            name='tour_type',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterField(
            model_name='tour',
            name='buses',
            field=models.ManyToManyField(related_name='buss', to='bus.bus'),
        ),
    ]
