# Generated by Django 4.0.6 on 2024-02-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_places_place'),
        ('tour', '0003_alter_tour_options_alter_tour_type_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='city',
        ),
        migrations.AddField(
            model_name='tour',
            name='city',
            field=models.ManyToManyField(related_name='citys', to='core.city'),
        ),
        migrations.RemoveField(
            model_name='tour',
            name='place',
        ),
        migrations.AddField(
            model_name='tour',
            name='place',
            field=models.ManyToManyField(related_name='places', to='core.place'),
        ),
    ]
