# Generated by Django 4.0.6 on 2024-02-20 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_remove_tour_city_tour_city_remove_tour_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour_type',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/tour_type/'),
        ),
    ]
