# Generated by Django 4.0.6 on 2024-02-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0006_alter_tour_itinerary'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='Itineratys',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
