# Generated by Django 4.0.6 on 2024-02-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_alter_hotel_overview_alter_hotel_review_rate_and_more'),
        ('tour', '0007_tour_itineratys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='Itinerary',
        ),
        migrations.AlterField(
            model_name='tour',
            name='Itineratys',
            field=models.JSONField(default=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tour',
            name='hotels',
            field=models.ManyToManyField(related_name='hotels', to='hotel.hotel'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='no_of_day',
            field=models.IntegerField(default=0),
        ),
    ]
