# Generated by Django 4.0.6 on 2024-02-23 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0009_alter_tour_map_link_alter_tour_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='Itineratys',
        ),
        migrations.AddField(
            model_name='tour',
            name='Itineraries',
            field=models.JSONField(default=dict),
        ),
    ]
