# Generated by Django 4.0.6 on 2024-02-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0010_remove_tour_itineratys_tour_itineraries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='rating',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
