# Generated by Django 4.0.6 on 2024-02-29 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0012_tour_tour_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour_booking',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.tour'),
        ),
    ]
