# Generated by Django 4.0.6 on 2024-03-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0013_alter_tour_booking_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour_booking',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tour_booking',
            name='phone_number',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour_booking',
            name='pyment_status',
            field=models.BooleanField(default=False),
        ),
    ]
