# Generated by Django 4.0.6 on 2024-03-01 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0015_rename_valid_date_from_tour_booking_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour_booking',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='tour_booking',
            name='start_date',
        ),
    ]
