# Generated by Django 4.0.6 on 2024-03-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0016_remove_tour_booking_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour_booking',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tour_booking',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
