# Generated by Django 4.0.6 on 2024-03-04 07:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tour', '0017_tour_booking_end_date_tour_booking_start_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tour_Review',
            new_name='TourReview',
        ),
    ]
