# Generated by Django 5.0.2 on 2024-03-09 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0018_rename_tour_review_tourreview'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tour_Type',
            new_name='TourType',
        ),
    ]
