# Generated by Django 5.0.2 on 2024-03-10 16:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0021_tourhistoryvisit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tour_Booking',
            new_name='TourBooking',
        ),
    ]
