# Generated by Django 5.0.2 on 2024-03-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0022_rename_tour_booking_tourbooking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourbooking',
            old_name='pyment_status',
            new_name='cancellation_status',
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
