# Generated by Django 5.0.2 on 2024-03-11 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0023_rename_pyment_status_tourbooking_cancellation_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourBookingName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('tour_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.tourbooking')),
            ],
        ),
    ]
