# Generated by Django 4.0.6 on 2024-03-15 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0026_touritinerary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='Itineraries',
            new_name='itineraries',
        ),
    ]
