# Generated by Django 4.0.6 on 2024-03-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0027_rename_itineraries_tour_itineraries'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='included',
            field=models.JSONField(default=dict),
        ),
    ]
