# Generated by Django 4.0.6 on 2024-03-19 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0029_alter_tour_image_2_alter_tour_image_3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='included',
        ),
        migrations.CreateModel(
            name='TourFacilitys',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.TextField(max_length=2000)),
                ('image', models.ImageField(upload_to='image/tour/facilitys')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.tour')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
