# Generated by Django 4.0.6 on 2024-03-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0032_tour_total_people_tour_tour_facility_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourfacility',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='tourvehicle',
            options={'ordering': ('created_at',)},
        ),
        migrations.AddField(
            model_name='tourvehicle',
            name='image',
            field=models.ImageField(default=0, upload_to='image/tour/vehicle'),
            preserve_default=False,
        ),
    ]
