# Generated by Django 4.1.3 on 2024-04-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0033_alter_tourfacility_options_alter_tourvehicle_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourimage',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterField(
            model_name='tour',
            name='map_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
