# Generated by Django 5.0 on 2024-02-18 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0004_rename_places_place"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bus",
            fields=[
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
                ("bus_number", models.IntegerField()),
                ("price", models.IntegerField()),
                ("rating", models.FloatField(default=0, null=True)),
                ("facility", models.CharField(max_length=100)),
                ("overview", models.CharField(max_length=500)),
                ("bus_company_image", models.ImageField(upload_to="image/hotel/")),
                ("bus_image", models.ImageField(upload_to="image/hotel/")),
                (
                    "end_point_city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="end_point_buses",
                        to="core.city",
                    ),
                ),
                (
                    "start_point_city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="start_point_buses",
                        to="core.city",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
            },
        ),
    ]
