# Generated by Django 4.0.6 on 2024-02-19 04:44

import bus.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='seat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='bus_company_image',
            field=models.ImageField(upload_to='image/bus/'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='bus_image',
            field=models.ImageField(upload_to='image/bus/'),
        ),
        migrations.CreateModel(
            name='Bus_Review',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rate', models.IntegerField(validators=[bus.models.Bus_Review.validate_max_value])),
                ('comment', models.CharField(max_length=100)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.bus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
