# Generated by Django 4.2.10 on 2024-02-09 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterField(
            model_name='city',
            name='code',
            field=models.CharField(max_length=4, unique=True),
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=100)),
                ('image', models.ImageField(upload_to='static/image/places')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.city')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
