# Generated by Django 4.2.10 on 2024-02-09 07:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_city_options_alter_state_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='image',
            field=models.ImageField(default=datetime.datetime(2024, 2, 9, 7, 38, 16, 439382, tzinfo=datetime.timezone.utc), upload_to='image/city'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='places',
            name='image',
            field=models.ImageField(upload_to='image/places'),
        ),
    ]
