# Generated by Django 4.0.6 on 2024-02-15 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_city_image_alter_places_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Places',
            new_name='Place',
        ),
    ]
