# Generated by Django 4.0.6 on 2024-03-15 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('created_at',)},
        ),
    ]
