# Generated by Django 5.0.2 on 2024-03-17 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_contact_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='location',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
